

LOCAL_PATH := $(call my-dir)

include $(CLEAR_VARS)

LOCAL_MODULE := libprotobuf
LOCAL_MODULE_FILENAME := libprotobuf

LOCAL_SRC_FILES := $(LOCAL_PATH)/../src/Modules/_bisectmodule.c \
$(LOCAL_PATH)/../src/Modules/_bz2module.c \
$(LOCAL_PATH)/../src/Modules/_codecsmodule.c \
$(LOCAL_PATH)/../src/Modules/_collectionsmodule.c \
$(LOCAL_PATH)/../src/Modules/_cryptmodule.c \
$(LOCAL_PATH)/../src/Modules/_csv.c \
$(LOCAL_PATH)/../src/Modules/_curses_panel.c \
$(LOCAL_PATH)/../src/Modules/_cursesmodule.c \
$(LOCAL_PATH)/../src/Modules/_datetimemodule.c \
$(LOCAL_PATH)/../src/Modules/_dbmmodule.c \
$(LOCAL_PATH)/../src/Modules/_elementtree.c \
$(LOCAL_PATH)/../src/Modules/_functoolsmodule.c \
$(LOCAL_PATH)/../src/Modules/_gdbmmodule.c \
$(LOCAL_PATH)/../src/Modules/_hashopenssl.c \
$(LOCAL_PATH)/../src/Modules/_heapqmodule.c \
$(LOCAL_PATH)/../src/Modules/_json.c \
$(LOCAL_PATH)/../src/Modules/_localemodule.c \
$(LOCAL_PATH)/../src/Modules/_lsprof.c \
$(LOCAL_PATH)/../src/Modules/_lzmamodule.c \
$(LOCAL_PATH)/../src/Modules/_math.c \
$(LOCAL_PATH)/../src/Modules/_opcode.c \
$(LOCAL_PATH)/../src/Modules/_operator.c \
$(LOCAL_PATH)/../src/Modules/_pickle.c \
$(LOCAL_PATH)/../src/Modules/_posixsubprocess.c \
$(LOCAL_PATH)/../src/Modules/_randommodule.c \
$(LOCAL_PATH)/../src/Modules/_scproxy.c \
$(LOCAL_PATH)/../src/Modules/_sre.c \
$(LOCAL_PATH)/../src/Modules/_ssl.c \
$(LOCAL_PATH)/../src/Modules/_stat.c \
$(LOCAL_PATH)/../src/Modules/_struct.c \
$(LOCAL_PATH)/../src/Modules/_testbuffer.c \
$(LOCAL_PATH)/../src/Modules/_testcapimodule.c \
$(LOCAL_PATH)/../src/Modules/_testimportmultiple.c \
$(LOCAL_PATH)/../src/Modules/_testmultiphase.c \
$(LOCAL_PATH)/../src/Modules/_threadmodule.c \
$(LOCAL_PATH)/../src/Modules/_tkinter.c \
$(LOCAL_PATH)/../src/Modules/_tracemalloc.c \
$(LOCAL_PATH)/../src/Modules/_weakref.c \
$(LOCAL_PATH)/../src/Modules/_winapi.c \
$(LOCAL_PATH)/../src/Modules/arraymodule.c \
$(LOCAL_PATH)/../src/Modules/atexitmodule.c \
$(LOCAL_PATH)/../src/Modules/audioop.c \
$(LOCAL_PATH)/../src/Modules/binascii.c \
$(LOCAL_PATH)/../src/Modules/cmathmodule.c \
$(LOCAL_PATH)/../src/Modules/errnomodule.c \
$(LOCAL_PATH)/../src/Modules/faulthandler.c \
$(LOCAL_PATH)/../src/Modules/fcntlmodule.c \
$(LOCAL_PATH)/../src/Modules/fpectlmodule.c \
$(LOCAL_PATH)/../src/Modules/fpetestmodule.c \
$(LOCAL_PATH)/../src/Modules/gcmodule.c \
$(LOCAL_PATH)/../src/Modules/getaddrinfo.c \
$(LOCAL_PATH)/../src/Modules/getbuildinfo.c \
$(LOCAL_PATH)/../src/Modules/getnameinfo.c \
$(LOCAL_PATH)/../src/Modules/getpath.c \
$(LOCAL_PATH)/../src/Modules/grpmodule.c \
$(LOCAL_PATH)/../src/Modules/hashtable.c \
$(LOCAL_PATH)/../src/Modules/itertoolsmodule.c \
$(LOCAL_PATH)/../src/Modules/main.c \
$(LOCAL_PATH)/../src/Modules/mathmodule.c \
$(LOCAL_PATH)/../src/Modules/md5module.c \
$(LOCAL_PATH)/../src/Modules/mmapmodule.c \
$(LOCAL_PATH)/../src/Modules/nismodule.c \
$(LOCAL_PATH)/../src/Modules/ossaudiodev.c \
$(LOCAL_PATH)/../src/Modules/overlapped.c \
$(LOCAL_PATH)/../src/Modules/parsermodule.c \
$(LOCAL_PATH)/../src/Modules/posixmodule.c \
$(LOCAL_PATH)/../src/Modules/pwdmodule.c \
$(LOCAL_PATH)/../src/Modules/pyexpat.c \
$(LOCAL_PATH)/../src/Modules/readline.c \
$(LOCAL_PATH)/../src/Modules/resource.c \
$(LOCAL_PATH)/../src/Modules/rotatingtree.c \
$(LOCAL_PATH)/../src/Modules/selectmodule.c \
$(LOCAL_PATH)/../src/Modules/sha1module.c \
$(LOCAL_PATH)/../src/Modules/sha256module.c \
$(LOCAL_PATH)/../src/Modules/sha512module.c \
$(LOCAL_PATH)/../src/Modules/signalmodule.c \
$(LOCAL_PATH)/../src/Modules/socketmodule.c \
$(LOCAL_PATH)/../src/Modules/spwdmodule.c \
$(LOCAL_PATH)/../src/Modules/symtablemodule.c \
$(LOCAL_PATH)/../src/Modules/syslogmodule.c \
$(LOCAL_PATH)/../src/Modules/termios.c \
$(LOCAL_PATH)/../src/Modules/timemodule.c \
$(LOCAL_PATH)/../src/Modules/tkappinit.c \
$(LOCAL_PATH)/../src/Modules/unicodedata.c \
$(LOCAL_PATH)/../src/Modules/xxlimited.c \
$(LOCAL_PATH)/../src/Modules/xxmodule.c \
$(LOCAL_PATH)/../src/Modules/xxsubtype.c \
$(LOCAL_PATH)/../src/Modules/zipimport.c \
$(LOCAL_PATH)/../src/Modules/zlibmodule.c \
$(LOCAL_PATH)/../src/Modules/_ctypes/_ctypes.c \
$(LOCAL_PATH)/../src/Modules/_ctypes/_ctypes_test.c \
$(LOCAL_PATH)/../src/Modules/_ctypes/callbacks.c \
$(LOCAL_PATH)/../src/Modules/_ctypes/callproc.c \
$(LOCAL_PATH)/../src/Modules/_ctypes/cfield.c \
$(LOCAL_PATH)/../src/Modules/_ctypes/malloc_closure.c \
$(LOCAL_PATH)/../src/Modules/_ctypes/stgdict.c \
$(LOCAL_PATH)/../src/Modules/_ctypes/darwin/dlfcn_simple.c \
$(LOCAL_PATH)/../src/Modules/_ctypes/libffi/src/closures.c \
$(LOCAL_PATH)/../src/Modules/_ctypes/libffi/src/debug.c \
$(LOCAL_PATH)/../src/Modules/_ctypes/libffi/src/dlmalloc.c \
$(LOCAL_PATH)/../src/Modules/_ctypes/libffi/src/java_raw_api.c \
$(LOCAL_PATH)/../src/Modules/_ctypes/libffi/src/prep_cif.c \
$(LOCAL_PATH)/../src/Modules/_ctypes/libffi/src/raw_api.c \
$(LOCAL_PATH)/../src/Modules/_ctypes/libffi/src/types.c \
$(LOCAL_PATH)/../src/Modules/_ctypes/libffi/src/aarch64/ffi.c \
$(LOCAL_PATH)/../src/Modules/_ctypes/libffi/src/alpha/ffi.c \
$(LOCAL_PATH)/../src/Modules/_ctypes/libffi/src/arc/ffi.c \
$(LOCAL_PATH)/../src/Modules/_ctypes/libffi/src/arm/ffi.c \
$(LOCAL_PATH)/../src/Modules/_ctypes/libffi/src/avr32/ffi.c \
$(LOCAL_PATH)/../src/Modules/_ctypes/libffi/src/bfin/ffi.c \
$(LOCAL_PATH)/../src/Modules/_ctypes/libffi/src/cris/ffi.c \
$(LOCAL_PATH)/../src/Modules/_ctypes/libffi/src/frv/ffi.c \
$(LOCAL_PATH)/../src/Modules/_ctypes/libffi/src/ia64/ffi.c \
$(LOCAL_PATH)/../src/Modules/_ctypes/libffi/src/m32r/ffi.c \
$(LOCAL_PATH)/../src/Modules/_ctypes/libffi/src/m68k/ffi.c \
$(LOCAL_PATH)/../src/Modules/_ctypes/libffi/src/m88k/ffi.c \
$(LOCAL_PATH)/../src/Modules/_ctypes/libffi/src/metag/ffi.c \
$(LOCAL_PATH)/../src/Modules/_ctypes/libffi/src/microblaze/ffi.c \
$(LOCAL_PATH)/../src/Modules/_ctypes/libffi/src/mips/ffi.c \
$(LOCAL_PATH)/../src/Modules/_ctypes/libffi/src/moxie/ffi.c \
$(LOCAL_PATH)/../src/Modules/_ctypes/libffi/src/nios2/ffi.c \
$(LOCAL_PATH)/../src/Modules/_ctypes/libffi/src/pa/ffi.c \
$(LOCAL_PATH)/../src/Modules/_ctypes/libffi/src/powerpc/ffi.c \
$(LOCAL_PATH)/../src/Modules/_ctypes/libffi/src/powerpc/ffi_darwin.c \
$(LOCAL_PATH)/../src/Modules/_ctypes/libffi/src/powerpc/ffi_linux64.c \
$(LOCAL_PATH)/../src/Modules/_ctypes/libffi/src/powerpc/ffi_sysv.c \
$(LOCAL_PATH)/../src/Modules/_ctypes/libffi/src/s390/ffi.c \
$(LOCAL_PATH)/../src/Modules/_ctypes/libffi/src/sh/ffi.c \
$(LOCAL_PATH)/../src/Modules/_ctypes/libffi/src/sh64/ffi.c \
$(LOCAL_PATH)/../src/Modules/_ctypes/libffi/src/sparc/ffi.c \
$(LOCAL_PATH)/../src/Modules/_ctypes/libffi/src/tile/ffi.c \
$(LOCAL_PATH)/../src/Modules/_ctypes/libffi/src/vax/ffi.c \
$(LOCAL_PATH)/../src/Modules/_ctypes/libffi/src/x86/ffi.c \
$(LOCAL_PATH)/../src/Modules/_ctypes/libffi/src/x86/ffi64.c \
$(LOCAL_PATH)/../src/Modules/_ctypes/libffi/src/xtensa/ffi.c \
$(LOCAL_PATH)/../src/Modules/_ctypes/libffi/testsuite/libffi.call/closure_fn0.c \
$(LOCAL_PATH)/../src/Modules/_ctypes/libffi/testsuite/libffi.call/closure_fn1.c \
$(LOCAL_PATH)/../src/Modules/_ctypes/libffi/testsuite/libffi.call/closure_fn2.c \
$(LOCAL_PATH)/../src/Modules/_ctypes/libffi/testsuite/libffi.call/closure_fn3.c \
$(LOCAL_PATH)/../src/Modules/_ctypes/libffi/testsuite/libffi.call/closure_fn4.c \
$(LOCAL_PATH)/../src/Modules/_ctypes/libffi/testsuite/libffi.call/closure_fn5.c \
$(LOCAL_PATH)/../src/Modules/_ctypes/libffi/testsuite/libffi.call/closure_fn6.c \
$(LOCAL_PATH)/../src/Modules/_ctypes/libffi/testsuite/libffi.call/closure_loc_fn0.c \
$(LOCAL_PATH)/../src/Modules/_ctypes/libffi/testsuite/libffi.call/closure_simple.c \
$(LOCAL_PATH)/../src/Modules/_ctypes/libffi/testsuite/libffi.call/cls_12byte.c \
$(LOCAL_PATH)/../src/Modules/_ctypes/libffi/testsuite/libffi.call/cls_16byte.c \
$(LOCAL_PATH)/../src/Modules/_ctypes/libffi/testsuite/libffi.call/cls_18byte.c \
$(LOCAL_PATH)/../src/Modules/_ctypes/libffi/testsuite/libffi.call/cls_19byte.c \
$(LOCAL_PATH)/../src/Modules/_ctypes/libffi/testsuite/libffi.call/cls_1_1byte.c \
$(LOCAL_PATH)/../src/Modules/_ctypes/libffi/testsuite/libffi.call/cls_20byte.c \
$(LOCAL_PATH)/../src/Modules/_ctypes/libffi/testsuite/libffi.call/cls_20byte1.c \
$(LOCAL_PATH)/../src/Modules/_ctypes/libffi/testsuite/libffi.call/cls_24byte.c \
$(LOCAL_PATH)/../src/Modules/_ctypes/libffi/testsuite/libffi.call/cls_2byte.c \
$(LOCAL_PATH)/../src/Modules/_ctypes/libffi/testsuite/libffi.call/cls_3_1byte.c \
$(LOCAL_PATH)/../src/Modules/_ctypes/libffi/testsuite/libffi.call/cls_3byte1.c \
$(LOCAL_PATH)/../src/Modules/_ctypes/libffi/testsuite/libffi.call/cls_3byte2.c \
$(LOCAL_PATH)/../src/Modules/_ctypes/libffi/testsuite/libffi.call/cls_4_1byte.c \
$(LOCAL_PATH)/../src/Modules/_ctypes/libffi/testsuite/libffi.call/cls_4byte.c \
$(LOCAL_PATH)/../src/Modules/_ctypes/libffi/testsuite/libffi.call/cls_5_1_byte.c \
$(LOCAL_PATH)/../src/Modules/_ctypes/libffi/testsuite/libffi.call/cls_5byte.c \
$(LOCAL_PATH)/../src/Modules/_ctypes/libffi/testsuite/libffi.call/cls_64byte.c \
$(LOCAL_PATH)/../src/Modules/_ctypes/libffi/testsuite/libffi.call/cls_6_1_byte.c \
$(LOCAL_PATH)/../src/Modules/_ctypes/libffi/testsuite/libffi.call/cls_6byte.c \
$(LOCAL_PATH)/../src/Modules/_ctypes/libffi/testsuite/libffi.call/cls_7_1_byte.c \
$(LOCAL_PATH)/../src/Modules/_ctypes/libffi/testsuite/libffi.call/cls_7byte.c \
$(LOCAL_PATH)/../src/Modules/_ctypes/libffi/testsuite/libffi.call/cls_8byte.c \
$(LOCAL_PATH)/../src/Modules/_ctypes/libffi/testsuite/libffi.call/cls_9byte1.c \
$(LOCAL_PATH)/../src/Modules/_ctypes/libffi/testsuite/libffi.call/cls_9byte2.c \
$(LOCAL_PATH)/../src/Modules/_ctypes/libffi/testsuite/libffi.call/cls_align_double.c \
$(LOCAL_PATH)/../src/Modules/_ctypes/libffi/testsuite/libffi.call/cls_align_float.c \
$(LOCAL_PATH)/../src/Modules/_ctypes/libffi/testsuite/libffi.call/cls_align_longdouble.c \
$(LOCAL_PATH)/../src/Modules/_ctypes/libffi/testsuite/libffi.call/cls_align_longdouble_split.c \
$(LOCAL_PATH)/../src/Modules/_ctypes/libffi/testsuite/libffi.call/cls_align_longdouble_split2.c \
$(LOCAL_PATH)/../src/Modules/_ctypes/libffi/testsuite/libffi.call/cls_align_pointer.c \
$(LOCAL_PATH)/../src/Modules/_ctypes/libffi/testsuite/libffi.call/cls_align_sint16.c \
$(LOCAL_PATH)/../src/Modules/_ctypes/libffi/testsuite/libffi.call/cls_align_sint32.c \
$(LOCAL_PATH)/../src/Modules/_ctypes/libffi/testsuite/libffi.call/cls_align_sint64.c \
$(LOCAL_PATH)/../src/Modules/_ctypes/libffi/testsuite/libffi.call/cls_align_uint16.c \
$(LOCAL_PATH)/../src/Modules/_ctypes/libffi/testsuite/libffi.call/cls_align_uint32.c \
$(LOCAL_PATH)/../src/Modules/_ctypes/libffi/testsuite/libffi.call/cls_align_uint64.c \
$(LOCAL_PATH)/../src/Modules/_ctypes/libffi/testsuite/libffi.call/cls_dbls_struct.c \
$(LOCAL_PATH)/../src/Modules/_ctypes/libffi/testsuite/libffi.call/cls_double.c \
$(LOCAL_PATH)/../src/Modules/_ctypes/libffi/testsuite/libffi.call/cls_double_va.c \
$(LOCAL_PATH)/../src/Modules/_ctypes/libffi/testsuite/libffi.call/cls_float.c \
$(LOCAL_PATH)/../src/Modules/_ctypes/libffi/testsuite/libffi.call/cls_longdouble.c \
$(LOCAL_PATH)/../src/Modules/_ctypes/libffi/testsuite/libffi.call/cls_longdouble_va.c \
$(LOCAL_PATH)/../src/Modules/_ctypes/libffi/testsuite/libffi.call/cls_multi_schar.c \
$(LOCAL_PATH)/../src/Modules/_ctypes/libffi/testsuite/libffi.call/cls_multi_sshort.c \
$(LOCAL_PATH)/../src/Modules/_ctypes/libffi/testsuite/libffi.call/cls_multi_sshortchar.c \
$(LOCAL_PATH)/../src/Modules/_ctypes/libffi/testsuite/libffi.call/cls_multi_uchar.c \
$(LOCAL_PATH)/../src/Modules/_ctypes/libffi/testsuite/libffi.call/cls_multi_ushort.c \
$(LOCAL_PATH)/../src/Modules/_ctypes/libffi/testsuite/libffi.call/cls_multi_ushortchar.c \
$(LOCAL_PATH)/../src/Modules/_ctypes/libffi/testsuite/libffi.call/cls_pointer.c \
$(LOCAL_PATH)/../src/Modules/_ctypes/libffi/testsuite/libffi.call/cls_pointer_stack.c \
$(LOCAL_PATH)/../src/Modules/_ctypes/libffi/testsuite/libffi.call/cls_schar.c \
$(LOCAL_PATH)/../src/Modules/_ctypes/libffi/testsuite/libffi.call/cls_sint.c \
$(LOCAL_PATH)/../src/Modules/_ctypes/libffi/testsuite/libffi.call/cls_sshort.c \
$(LOCAL_PATH)/../src/Modules/_ctypes/libffi/testsuite/libffi.call/cls_struct_va1.c \
$(LOCAL_PATH)/../src/Modules/_ctypes/libffi/testsuite/libffi.call/cls_uchar.c \
$(LOCAL_PATH)/../src/Modules/_ctypes/libffi/testsuite/libffi.call/cls_uchar_va.c \
$(LOCAL_PATH)/../src/Modules/_ctypes/libffi/testsuite/libffi.call/cls_uint.c \
$(LOCAL_PATH)/../src/Modules/_ctypes/libffi/testsuite/libffi.call/cls_uint_va.c \
$(LOCAL_PATH)/../src/Modules/_ctypes/libffi/testsuite/libffi.call/cls_ulong_va.c \
$(LOCAL_PATH)/../src/Modules/_ctypes/libffi/testsuite/libffi.call/cls_ulonglong.c \
$(LOCAL_PATH)/../src/Modules/_ctypes/libffi/testsuite/libffi.call/cls_ushort.c \
$(LOCAL_PATH)/../src/Modules/_ctypes/libffi/testsuite/libffi.call/cls_ushort_va.c \
$(LOCAL_PATH)/../src/Modules/_ctypes/libffi/testsuite/libffi.call/err_bad_abi.c \
$(LOCAL_PATH)/../src/Modules/_ctypes/libffi/testsuite/libffi.call/err_bad_typedef.c \
$(LOCAL_PATH)/../src/Modules/_ctypes/libffi/testsuite/libffi.call/float.c \
$(LOCAL_PATH)/../src/Modules/_ctypes/libffi/testsuite/libffi.call/float1.c \
$(LOCAL_PATH)/../src/Modules/_ctypes/libffi/testsuite/libffi.call/float2.c \
$(LOCAL_PATH)/../src/Modules/_ctypes/libffi/testsuite/libffi.call/float3.c \
$(LOCAL_PATH)/../src/Modules/_ctypes/libffi/testsuite/libffi.call/float4.c \
$(LOCAL_PATH)/../src/Modules/_ctypes/libffi/testsuite/libffi.call/float_va.c \
$(LOCAL_PATH)/../src/Modules/_ctypes/libffi/testsuite/libffi.call/huge_struct.c \
$(LOCAL_PATH)/../src/Modules/_ctypes/libffi/testsuite/libffi.call/many.c \
$(LOCAL_PATH)/../src/Modules/_ctypes/libffi/testsuite/libffi.call/many2.c \
$(LOCAL_PATH)/../src/Modules/_ctypes/libffi/testsuite/libffi.call/negint.c \
$(LOCAL_PATH)/../src/Modules/_ctypes/libffi/testsuite/libffi.call/nested_struct.c \
$(LOCAL_PATH)/../src/Modules/_ctypes/libffi/testsuite/libffi.call/nested_struct1.c \
$(LOCAL_PATH)/../src/Modules/_ctypes/libffi/testsuite/libffi.call/nested_struct10.c \
$(LOCAL_PATH)/../src/Modules/_ctypes/libffi/testsuite/libffi.call/nested_struct11.c \
$(LOCAL_PATH)/../src/Modules/_ctypes/libffi/testsuite/libffi.call/nested_struct2.c \
$(LOCAL_PATH)/../src/Modules/_ctypes/libffi/testsuite/libffi.call/nested_struct3.c \
$(LOCAL_PATH)/../src/Modules/_ctypes/libffi/testsuite/libffi.call/nested_struct4.c \
$(LOCAL_PATH)/../src/Modules/_ctypes/libffi/testsuite/libffi.call/nested_struct5.c \
$(LOCAL_PATH)/../src/Modules/_ctypes/libffi/testsuite/libffi.call/nested_struct6.c \
$(LOCAL_PATH)/../src/Modules/_ctypes/libffi/testsuite/libffi.call/nested_struct7.c \
$(LOCAL_PATH)/../src/Modules/_ctypes/libffi/testsuite/libffi.call/nested_struct8.c \
$(LOCAL_PATH)/../src/Modules/_ctypes/libffi/testsuite/libffi.call/nested_struct9.c \
$(LOCAL_PATH)/../src/Modules/_ctypes/libffi/testsuite/libffi.call/problem1.c \
$(LOCAL_PATH)/../src/Modules/_ctypes/libffi/testsuite/libffi.call/promotion.c \
$(LOCAL_PATH)/../src/Modules/_ctypes/libffi/testsuite/libffi.call/pyobjc-tc.c \
$(LOCAL_PATH)/../src/Modules/_ctypes/libffi/testsuite/libffi.call/return_dbl.c \
$(LOCAL_PATH)/../src/Modules/_ctypes/libffi/testsuite/libffi.call/return_dbl1.c \
$(LOCAL_PATH)/../src/Modules/_ctypes/libffi/testsuite/libffi.call/return_dbl2.c \
$(LOCAL_PATH)/../src/Modules/_ctypes/libffi/testsuite/libffi.call/return_fl.c \
$(LOCAL_PATH)/../src/Modules/_ctypes/libffi/testsuite/libffi.call/return_fl1.c \
$(LOCAL_PATH)/../src/Modules/_ctypes/libffi/testsuite/libffi.call/return_fl2.c \
$(LOCAL_PATH)/../src/Modules/_ctypes/libffi/testsuite/libffi.call/return_fl3.c \
$(LOCAL_PATH)/../src/Modules/_ctypes/libffi/testsuite/libffi.call/return_ldl.c \
$(LOCAL_PATH)/../src/Modules/_ctypes/libffi/testsuite/libffi.call/return_ll.c \
$(LOCAL_PATH)/../src/Modules/_ctypes/libffi/testsuite/libffi.call/return_ll1.c \
$(LOCAL_PATH)/../src/Modules/_ctypes/libffi/testsuite/libffi.call/return_sc.c \
$(LOCAL_PATH)/../src/Modules/_ctypes/libffi/testsuite/libffi.call/return_sl.c \
$(LOCAL_PATH)/../src/Modules/_ctypes/libffi/testsuite/libffi.call/return_uc.c \
$(LOCAL_PATH)/../src/Modules/_ctypes/libffi/testsuite/libffi.call/return_ul.c \
$(LOCAL_PATH)/../src/Modules/_ctypes/libffi/testsuite/libffi.call/stret_large.c \
$(LOCAL_PATH)/../src/Modules/_ctypes/libffi/testsuite/libffi.call/stret_large2.c \
$(LOCAL_PATH)/../src/Modules/_ctypes/libffi/testsuite/libffi.call/stret_medium.c \
$(LOCAL_PATH)/../src/Modules/_ctypes/libffi/testsuite/libffi.call/stret_medium2.c \
$(LOCAL_PATH)/../src/Modules/_ctypes/libffi/testsuite/libffi.call/strlen.c \
$(LOCAL_PATH)/../src/Modules/_ctypes/libffi/testsuite/libffi.call/strlen2.c \
$(LOCAL_PATH)/../src/Modules/_ctypes/libffi/testsuite/libffi.call/strlen3.c \
$(LOCAL_PATH)/../src/Modules/_ctypes/libffi/testsuite/libffi.call/strlen4.c \
$(LOCAL_PATH)/../src/Modules/_ctypes/libffi/testsuite/libffi.call/struct1.c \
$(LOCAL_PATH)/../src/Modules/_ctypes/libffi/testsuite/libffi.call/struct2.c \
$(LOCAL_PATH)/../src/Modules/_ctypes/libffi/testsuite/libffi.call/struct3.c \
$(LOCAL_PATH)/../src/Modules/_ctypes/libffi/testsuite/libffi.call/struct4.c \
$(LOCAL_PATH)/../src/Modules/_ctypes/libffi/testsuite/libffi.call/struct5.c \
$(LOCAL_PATH)/../src/Modules/_ctypes/libffi/testsuite/libffi.call/struct6.c \
$(LOCAL_PATH)/../src/Modules/_ctypes/libffi/testsuite/libffi.call/struct7.c \
$(LOCAL_PATH)/../src/Modules/_ctypes/libffi/testsuite/libffi.call/struct8.c \
$(LOCAL_PATH)/../src/Modules/_ctypes/libffi/testsuite/libffi.call/struct9.c \
$(LOCAL_PATH)/../src/Modules/_ctypes/libffi/testsuite/libffi.call/testclosure.c \
$(LOCAL_PATH)/../src/Modules/_ctypes/libffi/testsuite/libffi.call/uninitialized.c \
$(LOCAL_PATH)/../src/Modules/_ctypes/libffi/testsuite/libffi.call/unwindtest.cc \
$(LOCAL_PATH)/../src/Modules/_ctypes/libffi/testsuite/libffi.call/unwindtest_ffi_call.cc \
$(LOCAL_PATH)/../src/Modules/_ctypes/libffi/testsuite/libffi.call/va_1.c \
$(LOCAL_PATH)/../src/Modules/_ctypes/libffi/testsuite/libffi.call/va_struct1.c \
$(LOCAL_PATH)/../src/Modules/_ctypes/libffi/testsuite/libffi.call/va_struct2.c \
$(LOCAL_PATH)/../src/Modules/_ctypes/libffi/testsuite/libffi.call/va_struct3.c \
$(LOCAL_PATH)/../src/Modules/_ctypes/libffi_arm_wince/debug.c \
$(LOCAL_PATH)/../src/Modules/_ctypes/libffi_arm_wince/ffi.c \
$(LOCAL_PATH)/../src/Modules/_ctypes/libffi_arm_wince/prep_cif.c \
$(LOCAL_PATH)/../src/Modules/_ctypes/libffi_msvc/ffi.c \
$(LOCAL_PATH)/../src/Modules/_ctypes/libffi_msvc/prep_cif.c \
$(LOCAL_PATH)/../src/Modules/_ctypes/libffi_msvc/types.c \
$(LOCAL_PATH)/../src/Modules/_ctypes/libffi_msvc/win32.c \
$(LOCAL_PATH)/../src/Modules/_ctypes/libffi_osx/ffi.c \
$(LOCAL_PATH)/../src/Modules/_ctypes/libffi_osx/types.c \
$(LOCAL_PATH)/../src/Modules/_ctypes/libffi_osx/powerpc/ppc-ffi_darwin.c \
$(LOCAL_PATH)/../src/Modules/_ctypes/libffi_osx/x86/x86-ffi64.c \
$(LOCAL_PATH)/../src/Modules/_ctypes/libffi_osx/x86/x86-ffi_darwin.c \
$(LOCAL_PATH)/../src/Modules/_decimal/_decimal.c \
$(LOCAL_PATH)/../src/Modules/_decimal/libmpdec/basearith.c \
$(LOCAL_PATH)/../src/Modules/_decimal/libmpdec/constants.c \
$(LOCAL_PATH)/../src/Modules/_decimal/libmpdec/context.c \
$(LOCAL_PATH)/../src/Modules/_decimal/libmpdec/convolute.c \
$(LOCAL_PATH)/../src/Modules/_decimal/libmpdec/crt.c \
$(LOCAL_PATH)/../src/Modules/_decimal/libmpdec/difradix2.c \
$(LOCAL_PATH)/../src/Modules/_decimal/libmpdec/fnt.c \
$(LOCAL_PATH)/../src/Modules/_decimal/libmpdec/fourstep.c \
$(LOCAL_PATH)/../src/Modules/_decimal/libmpdec/io.c \
$(LOCAL_PATH)/../src/Modules/_decimal/libmpdec/memory.c \
$(LOCAL_PATH)/../src/Modules/_decimal/libmpdec/mpdecimal.c \
$(LOCAL_PATH)/../src/Modules/_decimal/libmpdec/numbertheory.c \
$(LOCAL_PATH)/../src/Modules/_decimal/libmpdec/sixstep.c \
$(LOCAL_PATH)/../src/Modules/_decimal/libmpdec/transpose.c \
$(LOCAL_PATH)/../src/Modules/_io/_iomodule.c \
$(LOCAL_PATH)/../src/Modules/_io/bufferedio.c \
$(LOCAL_PATH)/../src/Modules/_io/bytesio.c \
$(LOCAL_PATH)/../src/Modules/_io/fileio.c \
$(LOCAL_PATH)/../src/Modules/_io/iobase.c \
$(LOCAL_PATH)/../src/Modules/_io/stringio.c \
$(LOCAL_PATH)/../src/Modules/_io/textio.c \
$(LOCAL_PATH)/../src/Modules/_multiprocessing/multiprocessing.c \
$(LOCAL_PATH)/../src/Modules/_multiprocessing/semaphore.c \
$(LOCAL_PATH)/../src/Modules/_sqlite/cache.c \
$(LOCAL_PATH)/../src/Modules/_sqlite/connection.c \
$(LOCAL_PATH)/../src/Modules/_sqlite/cursor.c \
$(LOCAL_PATH)/../src/Modules/_sqlite/microprotocols.c \
$(LOCAL_PATH)/../src/Modules/_sqlite/module.c \
$(LOCAL_PATH)/../src/Modules/_sqlite/prepare_protocol.c \
$(LOCAL_PATH)/../src/Modules/_sqlite/row.c \
$(LOCAL_PATH)/../src/Modules/_sqlite/statement.c \
$(LOCAL_PATH)/../src/Modules/_sqlite/util.c \
$(LOCAL_PATH)/../src/Modules/cjkcodecs/_codecs_cn.c \
$(LOCAL_PATH)/../src/Modules/cjkcodecs/_codecs_hk.c \
$(LOCAL_PATH)/../src/Modules/cjkcodecs/_codecs_iso2022.c \
$(LOCAL_PATH)/../src/Modules/cjkcodecs/_codecs_jp.c \
$(LOCAL_PATH)/../src/Modules/cjkcodecs/_codecs_kr.c \
$(LOCAL_PATH)/../src/Modules/cjkcodecs/_codecs_tw.c \
$(LOCAL_PATH)/../src/Modules/cjkcodecs/multibytecodec.c \
$(LOCAL_PATH)/../src/Modules/expat/xmlparse.c \
$(LOCAL_PATH)/../src/Modules/expat/xmlrole.c \
$(LOCAL_PATH)/../src/Modules/expat/xmltok.c \
$(LOCAL_PATH)/../src/Modules/expat/xmltok_impl.c \
$(LOCAL_PATH)/../src/Modules/expat/xmltok_ns.c \
$(LOCAL_PATH)/../src/Modules/zlib/adler32.c \
$(LOCAL_PATH)/../src/Modules/zlib/compress.c \
$(LOCAL_PATH)/../src/Modules/zlib/crc32.c \
$(LOCAL_PATH)/../src/Modules/zlib/deflate.c \
$(LOCAL_PATH)/../src/Modules/zlib/example.c \
$(LOCAL_PATH)/../src/Modules/zlib/gzclose.c \
$(LOCAL_PATH)/../src/Modules/zlib/gzlib.c \
$(LOCAL_PATH)/../src/Modules/zlib/gzread.c \
$(LOCAL_PATH)/../src/Modules/zlib/gzwrite.c \
$(LOCAL_PATH)/../src/Modules/zlib/infback.c \
$(LOCAL_PATH)/../src/Modules/zlib/inffast.c \
$(LOCAL_PATH)/../src/Modules/zlib/inflate.c \
$(LOCAL_PATH)/../src/Modules/zlib/inftrees.c \
$(LOCAL_PATH)/../src/Modules/zlib/minigzip.c \
$(LOCAL_PATH)/../src/Modules/zlib/trees.c \
$(LOCAL_PATH)/../src/Modules/zlib/uncompr.c \
$(LOCAL_PATH)/../src/Modules/zlib/zutil.c \
$(LOCAL_PATH)/../src/Objects/abstract.c \
$(LOCAL_PATH)/../src/Objects/accu.c \
$(LOCAL_PATH)/../src/Objects/boolobject.c \
$(LOCAL_PATH)/../src/Objects/bytearrayobject.c \
$(LOCAL_PATH)/../src/Objects/bytes_methods.c \
$(LOCAL_PATH)/../src/Objects/bytesobject.c \
$(LOCAL_PATH)/../src/Objects/capsule.c \
$(LOCAL_PATH)/../src/Objects/cellobject.c \
$(LOCAL_PATH)/../src/Objects/classobject.c \
$(LOCAL_PATH)/../src/Objects/codeobject.c \
$(LOCAL_PATH)/../src/Objects/complexobject.c \
$(LOCAL_PATH)/../src/Objects/descrobject.c \
$(LOCAL_PATH)/../src/Objects/dictobject.c \
$(LOCAL_PATH)/../src/Objects/enumobject.c \
$(LOCAL_PATH)/../src/Objects/exceptions.c \
$(LOCAL_PATH)/../src/Objects/fileobject.c \
$(LOCAL_PATH)/../src/Objects/floatobject.c \
$(LOCAL_PATH)/../src/Objects/frameobject.c \
$(LOCAL_PATH)/../src/Objects/funcobject.c \
$(LOCAL_PATH)/../src/Objects/genobject.c \
$(LOCAL_PATH)/../src/Objects/iterobject.c \
$(LOCAL_PATH)/../src/Objects/listobject.c \
$(LOCAL_PATH)/../src/Objects/longobject.c \
$(LOCAL_PATH)/../src/Objects/memoryobject.c \
$(LOCAL_PATH)/../src/Objects/methodobject.c \
$(LOCAL_PATH)/../src/Objects/moduleobject.c \
$(LOCAL_PATH)/../src/Objects/namespaceobject.c \
$(LOCAL_PATH)/../src/Objects/object.c \
$(LOCAL_PATH)/../src/Objects/obmalloc.c \
$(LOCAL_PATH)/../src/Objects/odictobject.c \
$(LOCAL_PATH)/../src/Objects/rangeobject.c \
$(LOCAL_PATH)/../src/Objects/setobject.c \
$(LOCAL_PATH)/../src/Objects/sliceobject.c \
$(LOCAL_PATH)/../src/Objects/structseq.c \
$(LOCAL_PATH)/../src/Objects/tupleobject.c \
$(LOCAL_PATH)/../src/Objects/typeobject.c \
$(LOCAL_PATH)/../src/Objects/unicodectype.c \
$(LOCAL_PATH)/../src/Objects/unicodeobject.c \
$(LOCAL_PATH)/../src/Objects/weakrefobject.c \
$(LOCAL_PATH)/../src/Parser/acceler.c \
$(LOCAL_PATH)/../src/Parser/bitset.c \
$(LOCAL_PATH)/../src/Parser/firstsets.c \
$(LOCAL_PATH)/../src/Parser/grammar.c \
$(LOCAL_PATH)/../src/Parser/grammar1.c \
$(LOCAL_PATH)/../src/Parser/listnode.c \
$(LOCAL_PATH)/../src/Parser/metagrammar.c \
$(LOCAL_PATH)/../src/Parser/myreadline.c \
$(LOCAL_PATH)/../src/Parser/node.c \
$(LOCAL_PATH)/../src/Parser/parser.c \
$(LOCAL_PATH)/../src/Parser/parsetok.c \
$(LOCAL_PATH)/../src/Parser/parsetok_pgen.c \
$(LOCAL_PATH)/../src/Parser/pgen.c \
$(LOCAL_PATH)/../src/Parser/pgenmain.c \
$(LOCAL_PATH)/../src/Parser/printgrammar.c \
$(LOCAL_PATH)/../src/Parser/tokenizer.c \
$(LOCAL_PATH)/../src/Parser/tokenizer_pgen.c \
$(LOCAL_PATH)/../src/Python/_warnings.c \
$(LOCAL_PATH)/../src/Python/asdl.c \
$(LOCAL_PATH)/../src/Python/ast.c \
$(LOCAL_PATH)/../src/Python/bltinmodule.c \
$(LOCAL_PATH)/../src/Python/ceval.c \
$(LOCAL_PATH)/../src/Python/codecs.c \
$(LOCAL_PATH)/../src/Python/compile.c \
$(LOCAL_PATH)/../src/Python/dtoa.c \
$(LOCAL_PATH)/../src/Python/dup2.c \
$(LOCAL_PATH)/../src/Python/dynamic_annotations.c \
$(LOCAL_PATH)/../src/Python/dynload_aix.c \
$(LOCAL_PATH)/../src/Python/dynload_dl.c \
$(LOCAL_PATH)/../src/Python/dynload_hpux.c \
$(LOCAL_PATH)/../src/Python/dynload_next.c \
$(LOCAL_PATH)/../src/Python/dynload_shlib.c \
$(LOCAL_PATH)/../src/Python/dynload_stub.c \
$(LOCAL_PATH)/../src/Python/dynload_win.c \
$(LOCAL_PATH)/../src/Python/errors.c \
$(LOCAL_PATH)/../src/Python/fileutils.c \
$(LOCAL_PATH)/../src/Python/formatter_unicode.c \
$(LOCAL_PATH)/../src/Python/frozen.c \
$(LOCAL_PATH)/../src/Python/frozenmain.c \
$(LOCAL_PATH)/../src/Python/future.c \
$(LOCAL_PATH)/../src/Python/getargs.c \
$(LOCAL_PATH)/../src/Python/getcompiler.c \
$(LOCAL_PATH)/../src/Python/getcopyright.c \
$(LOCAL_PATH)/../src/Python/getopt.c \
$(LOCAL_PATH)/../src/Python/getplatform.c \
$(LOCAL_PATH)/../src/Python/getversion.c \
$(LOCAL_PATH)/../src/Python/graminit.c \
$(LOCAL_PATH)/../src/Python/import.c \
$(LOCAL_PATH)/../src/Python/importdl.c \
$(LOCAL_PATH)/../src/Python/marshal.c \
$(LOCAL_PATH)/../src/Python/modsupport.c \
$(LOCAL_PATH)/../src/Python/mysnprintf.c \
$(LOCAL_PATH)/../src/Python/mystrtoul.c \
$(LOCAL_PATH)/../src/Python/peephole.c \
$(LOCAL_PATH)/../src/Python/pyarena.c \
$(LOCAL_PATH)/../src/Python/pyctype.c \
$(LOCAL_PATH)/../src/Python/pyfpe.c \
$(LOCAL_PATH)/../src/Python/pyhash.c \
$(LOCAL_PATH)/../src/Python/pylifecycle.c \
$(LOCAL_PATH)/../src/Python/pymath.c \
$(LOCAL_PATH)/../src/Python/pystate.c \
$(LOCAL_PATH)/../src/Python/pystrcmp.c \
$(LOCAL_PATH)/../src/Python/pystrhex.c \
$(LOCAL_PATH)/../src/Python/pystrtod.c \
$(LOCAL_PATH)/../src/Python/Python-ast.c \
$(LOCAL_PATH)/../src/Python/pythonrun.c \
$(LOCAL_PATH)/../src/Python/pytime.c \
$(LOCAL_PATH)/../src/Python/random.c \
$(LOCAL_PATH)/../src/Python/sigcheck.c \
$(LOCAL_PATH)/../src/Python/strdup.c \
$(LOCAL_PATH)/../src/Python/structmember.c \
$(LOCAL_PATH)/../src/Python/symtable.c \
$(LOCAL_PATH)/../src/Python/sysmodule.c \
$(LOCAL_PATH)/../src/Python/thread.c \
$(LOCAL_PATH)/../src/Python/traceback.c

LOCAL_C_INCLUDES := $(LOCAL_PATH)/../src/Include \
$(LOCAL_PATH)/../src/Modules \
$(LOCAL_PATH)/../src/Objects \
$(LOCAL_PATH)/../src/Parser \
$(LOCAL_PATH)/../src/Python \
$(LOCAL_PATH)/../src/Modules/_ctypes \
$(LOCAL_PATH)/../src/Modules/_decimal \
$(LOCAL_PATH)/../src/Modules/_io \
$(LOCAL_PATH)/../src/Modules/_multiprocessing \
$(LOCAL_PATH)/../src/Modules/_sqlite \
$(LOCAL_PATH)/../src/Modules/cjkcodecs \
$(LOCAL_PATH)/../src/Modules/clinic \
$(LOCAL_PATH)/../src/Modules/expat \
$(LOCAL_PATH)/../src/Modules/zlib \
$(LOCAL_PATH)/../src/Modules/_ctypes/darwin \
$(LOCAL_PATH)/../src/Modules/_ctypes/libffi \
$(LOCAL_PATH)/../src/Modules/_ctypes/libffi_arm_wince \
$(LOCAL_PATH)/../src/Modules/_ctypes/libffi_msvc \
$(LOCAL_PATH)/../src/Modules/_ctypes/libffi_osx \
$(LOCAL_PATH)/../src/Modules/_ctypes/libffi/doc \
$(LOCAL_PATH)/../src/Modules/_ctypes/libffi/include \
$(LOCAL_PATH)/../src/Modules/_ctypes/libffi/libffi.xcodeproj \
$(LOCAL_PATH)/../src/Modules/_ctypes/libffi/m4 \
$(LOCAL_PATH)/../src/Modules/_ctypes/libffi/man \
$(LOCAL_PATH)/../src/Modules/_ctypes/libffi/src \
$(LOCAL_PATH)/../src/Modules/_ctypes/libffi/testsuite \
$(LOCAL_PATH)/../src/Modules/_ctypes/libffi/src/aarch64 \
$(LOCAL_PATH)/../src/Modules/_ctypes/libffi/src/alpha \
$(LOCAL_PATH)/../src/Modules/_ctypes/libffi/src/arc \
$(LOCAL_PATH)/../src/Modules/_ctypes/libffi/src/arm \
$(LOCAL_PATH)/../src/Modules/_ctypes/libffi/src/avr32 \
$(LOCAL_PATH)/../src/Modules/_ctypes/libffi/src/bfin \
$(LOCAL_PATH)/../src/Modules/_ctypes/libffi/src/cris \
$(LOCAL_PATH)/../src/Modules/_ctypes/libffi/src/frv \
$(LOCAL_PATH)/../src/Modules/_ctypes/libffi/src/ia64 \
$(LOCAL_PATH)/../src/Modules/_ctypes/libffi/src/m32r \
$(LOCAL_PATH)/../src/Modules/_ctypes/libffi/src/m68k \
$(LOCAL_PATH)/../src/Modules/_ctypes/libffi/src/m88k \
$(LOCAL_PATH)/../src/Modules/_ctypes/libffi/src/metag \
$(LOCAL_PATH)/../src/Modules/_ctypes/libffi/src/microblaze \
$(LOCAL_PATH)/../src/Modules/_ctypes/libffi/src/mips \
$(LOCAL_PATH)/../src/Modules/_ctypes/libffi/src/moxie \
$(LOCAL_PATH)/../src/Modules/_ctypes/libffi/src/nios2 \
$(LOCAL_PATH)/../src/Modules/_ctypes/libffi/src/pa \
$(LOCAL_PATH)/../src/Modules/_ctypes/libffi/src/powerpc \
$(LOCAL_PATH)/../src/Modules/_ctypes/libffi/src/s390 \
$(LOCAL_PATH)/../src/Modules/_ctypes/libffi/src/sh \
$(LOCAL_PATH)/../src/Modules/_ctypes/libffi/src/sh64 \
$(LOCAL_PATH)/../src/Modules/_ctypes/libffi/src/sparc \
$(LOCAL_PATH)/../src/Modules/_ctypes/libffi/src/tile \
$(LOCAL_PATH)/../src/Modules/_ctypes/libffi/src/vax \
$(LOCAL_PATH)/../src/Modules/_ctypes/libffi/src/x86 \
$(LOCAL_PATH)/../src/Modules/_ctypes/libffi/src/xtensa \
$(LOCAL_PATH)/../src/Modules/_ctypes/libffi/testsuite/config \
$(LOCAL_PATH)/../src/Modules/_ctypes/libffi/testsuite/lib \
$(LOCAL_PATH)/../src/Modules/_ctypes/libffi/testsuite/libffi.call \
$(LOCAL_PATH)/../src/Modules/_ctypes/libffi_osx/include \
$(LOCAL_PATH)/../src/Modules/_ctypes/libffi_osx/powerpc \
$(LOCAL_PATH)/../src/Modules/_ctypes/libffi_osx/x86 \
$(LOCAL_PATH)/../src/Modules/_decimal/libmpdec \
$(LOCAL_PATH)/../src/Modules/_decimal/tests \
$(LOCAL_PATH)/../src/Modules/_decimal/libmpdec/literature \
$(LOCAL_PATH)/../src/Modules/_io/clinic \
$(LOCAL_PATH)/../src/Modules/cjkcodecs/clinic \
$(LOCAL_PATH)/../src/Objects/clinic \
$(LOCAL_PATH)/../src/Objects/stringlib \
$(LOCAL_PATH)/../src/Python/clinic

include $(BUILD_STATIC_LIBRARY)

